version: "3.9"

services: 
  database:
    image: postgres
    container_name: app_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app-db
    volumes: 
      - pgdata:/data/postgres

  app: 
    build: .
    container_name: boiler_app
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - app_database
    depends_on:
      - app_database



volumes:
  pgdata:
    driver: local